[General]
Debug = true
# workers
Workers = 300
# GoogleTranslate or Cloudflare
UsedFor = "GoogleTranslate"

[Ping]
# avaivable values: icmp, tcp, udp
Protocol = "icmp"
# Port for tcp and udp, icmp will ignore port
Port = 443
# Times of tests per IP
Count = 3
# Millisecond
Timeout = 500
# true: it's legal if it succeeds every time. false: it's legal if it has one succeeds
all = false

[HTTP]
# Standard HTTPS ports are 443 and 8443.
Port = 443
# Times of tests per IP
Count = 3
# Millisecond
Timeout = 2000
# true: it's legal if it succeeds every time. false: it's legal if it has one succeeds
all = false

[UsedFor]

[UsedFor.Cloudflare]
IPRangesFile = "./data/cloudflare.json"
CustomIPRangesFile = "./data/cloudflare_custom_ip_ranges.txt"
IPOutputFile = "./data/output_cloudflare.txt"
WithIPv6 = false
HttpsURL = "https://yezheng.pages.dev"

[UsedFor.GoogleTranslate]
IPRangesFile = "./data/goog.json"
CustomIPRangesFile = "./data/google_translate_custom_ip_ranges.txt"
IPOutputFile = "./data/output_google_translate.txt"
WithIPv6 = false
HttpsURL = "https://translate.google.com"